### ISSUE TITLE
Add Lychee-front package

### ISSUE THREAD

**Issue by mostlyjason** [linuxserver/docker-lychee#18]
The Lychee-front package was never added as described in #10 Please add or reopen that issue.

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by thelamer** [comment]
@mostlyjason we pull their releases from here : 
https://github.com/LycheeOrg/Lychee/releases

These packages include Lychee-Front
