### ISSUE TITLE
Fresh install; Server error or API not found

### ISSUE THREAD

**Issue by wouterverduin** [linuxserver/docker-lychee#25]
Just installed using the docker compose after modifying for my personal use:

---
version: "2"
services:
  lychee:
    image: linuxserver/lychee
    container_name: lychee
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - ~/lychee:/config
      - /MEDIA/Fotos:/pictures
    ports:
      - 96:80
    restart: unless-stopped

So; installed it through docker compose the same way i used to do with other Linuxserver docker images. However, i got the error "Server error or API not found".
Wat am i doing wrong? 

In the logs i found this: 
2019/07/03 19:32:58 [error] 312#312: *14 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.146, server: _, request: "POST /php/index.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "$

Looks i somewhere need to allow external acces, only how?!

Thanks for the help in advance!

**Comment by tobbenb** [comment]
Don't run it as root. Change it to the user that have access to the config folder on the host.

**Comment by wouterverduin** [comment]
I run it as root in a separate vm. Both folders are owned by root so that cant be the problem..

**Comment by aptalca** [comment]
That precisely is the problem
