### ISSUE TITLE
"No such file or directory" message when localhost is configured

### ISSUE THREAD

**Issue by rinyakok** [linuxserver/docker-lychee#27]
Hello,

I run Lychee with Mariadb from dockers on OMV4 running on RPI4.
I managed to configure the database and use the Lychee when I entered the actual IP address of my device once the database was created.

Since my 4G rooter assigns a new/different IP address to my device, sometimes I cannot access the database because the IP is hardcoded in config.php.

I thought when I change it to localhost, would solve the problem, but unfortunately it didn't.

When I changed the $dbHost from a real IP address to 'localhost' I got the following error message from Lychee:
 "No such file or directory"

What could be the problem ?

Any suggestion how to solve it ?

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by aptalca** [comment]
If you put them on the same user defined bridge network, you can access it by container name
https://blog.linuxserver.io/2017/10/17/using-docker-networks-for-better-inter-container-communication/

**Comment by rinyakok** [comment]
yes. it solved the issue.

Thank you for the hint and support.
