### ISSUE TITLE
Update URLs to point to new Lychee Org

### ISSUE THREAD

**Issue by stumpylog** [linuxserver/docker-lychee#28]
Super minor thing, related to #7, the internals got updated to the new repository under the organization, but the URL for both the link and the Lychee logo still point to Electerious.

Current URL: https://lychee.electerious.com
Expected URL: https://lycheeorg.github.io/ (as seen at https://github.com/LycheeOrg/Lychee)

**Comment by aptalca** [comment]
Thanks for the heads up
