### ISSUE TITLE
Lychee version 4 beta 1 release

### ISSUE THREAD

**Issue by deltabweb** [linuxserver/docker-lychee#30]
Hi,
Are you planning to release an image for the new version of Lychee?
The version 4 beta 1 is out in this repository:
https://github.com/LycheeOrg/Lychee-Laravel/releases

**Comment by aptalca** [comment]
we have a dev branch here on github, but we are not publishing images yet: https://github.com/linuxserver/docker-lychee/tree/lychee-laravel-upgrade

**Comment by deltabweb** [comment]
Thanks for the info, I'll have a look
Any plan on publishing images anytime soon? Or are you just waiting for a stable release?

**Comment by aptalca** [comment]
Probably will wait until stable
