### ISSUE TITLE
Unable to connect to host database.

### ISSUE THREAD

**Issue by Thijxx** [linuxserver/docker-lychee#37]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
The application should create it's own database.

## Current Behavior
The first screen in the web interface is about a database connection. If I do not fill in anything, it errors. If I only fill in a username and password, it tells me access is denied. The docker-image cannot be used.

## Steps to Reproduce

1. Run container
2. Browse to the web UI
3. Try to create a database

## Environment
**OS:**      Centos7
**CPU architecture:** x86_64
**How docker service was installed:**      
Portianer, Stack, docker-compose copy/paste with changed paths and changed port.

## Command used to create docker container (run/create/compose/screenshot)
Portainer UI

## Docker logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.


[s6-init] ensuring user provided files have correct perms...exited 0.


[fix-attrs.d] applying ownership & permissions fixes...


[fix-attrs.d] done.


[cont-init.d] executing container initialization scripts...


[cont-init.d] 01-envfile: executing... 


[cont-init.d] 01-envfile: exited 0.


[cont-init.d] 10-adduser: executing... 


-------------------------------------


          _         ()


         | |  ___   _    __


         | | / __| | |  /  \ 


         | | \__ \ | | | () |


         |_| |___/ |_|  \__/


Brought to you by linuxserver.io


-------------------------------------


To support LSIO projects visit:


https://www.linuxserver.io/donate/


-------------------------------------


GID/UID


-------------------------------------


User uid:    1000


User gid:    1000


-------------------------------------


[cont-init.d] 10-adduser: exited 0.


[cont-init.d] 20-config: executing... 


[cont-init.d] 20-config: exited 0.


[cont-init.d] 30-keygen: executing... 


generating self-signed keys in /config/keys, you can replace these with your own keys if required


Generating a RSA private key




+


..+++++


writing new private key to '/config/keys/cert.key'


-----


[cont-init.d] 30-keygen: exited 0.


[cont-init.d] 40-config: executing... 


[cont-init.d] 40-config: exited 0.


[cont-init.d] 99-custom-files: executing... 


[custom-init] no custom files found exiting...


[cont-init.d] 99-custom-files: exited 0.


[cont-init.d] done.


[services.d] starting services


[services.d] done.
```

**Comment by j0nnymoe** [comment]
You need to supply your own MySQL/MariaDB instance for this container to connect to. We do not bundle this in the container.

**Comment by tobbenb** [comment]
You have not included the error messages, but it sounds like you do not have a database setup and therefore not filling in the info about the database connection.
