### ISSUE TITLE
Can't  browse to site after creating container

### ISSUE THREAD

**Issue by whisperdancer** [linuxserver/docker-lychee#39]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

Should browse to site and see lychee in browser

## Current Behavior

Can't browse to site. Get 404 error. Checked nginx logs. And this error appears.

2020/07/31 19:47:57 [error] 361#361: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught InvalidArgumentException: Please provide a valid cache path. in /app/lychee/vendor/laravel/framework/src/Illuminate/View/Compilers/Compiler.php:36

I googled the error and it appears the solution may be having to create the folder that's missing. 

## Steps to Reproduce

1. Run compose and access site in browser
2.
3.
4.

## Environment
**OS:**      Raspberry OS
**CPU architecture:** x86_64/arm32/arm64      Armf7

Here are the log files for container log https://pastebin.com/ZJ5paQZ0 and nginx log https://pastebin.com/jdxDc0nF and compose https://pastebin.com/5G9ufdeq

**Comment by j0nnymoe** [comment]
Where does `${USERDIR}` point to?

**Comment by j0nnymoe** [comment]
closing due to no response.
