### ISSUE TITLE
Lychee container starts but does not run lychee

### ISSUE THREAD

**Issue by kevinlowen1** [linuxserver/docker-lychee#45]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Lychee should start in a docker container and should be reachable on port 8080 per the docker commands used to create the container

## Current Behavior

Docker container is started but there are error messages in the logs for lychee and the lychee app is not reachable on the port it should be running on.  No error message, just browser saying it cannot connect.

log files below:
[_lychee_logs-2.txt](https://github.com/linuxserver/docker-lychee/files/6173507/_lychee_logs-2.txt)
[_lychee_logs-1.txt](https://github.com/linuxserver/docker-lychee/files/6173500/_lychee_logs-1.txt)

## Steps to Reproduce

docker cli command used is below:

```
docker run -d \
  --name=lychee \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=America/New_York \
  -e DB_HOST=mariadb \
  -e DB_USERNAME=lychee \
  -e DB_PASSWORD=passwordToDbHere \
  -e DB_DATABASE=lychee \
  -p 8080:80 \
  -v /srv/dev-disk-by-uuid-e790ab10-05b5-4446-be4f-761b1fdd1e7b/appdata/lychee:/config \
  -v /srv/dev-disk-by-uuid-e790ab10-05b5-4446-be4f-761b1fdd1e7b/media/photos:/pictures \
  --restart unless-stopped \
  ghcr.io/linuxserver/lychee
```

The database lychee should be using was created separately and the username/password to connect to the db were created manually.
The db is a mariadb container named lychee_db, it is reachable on port 3306 (standard port).

The db was created separately bcs I was running into an issue when creating both the db and the lychee container at the same time in one stack.

## Environment
**OS:**
Raspbian running OMV and Portainer.
Docker/Portainer is on an external hdd not the main drive
**CPU architecture:** x86_64/arm32/arm64
arm64
**How docker service was installed:**

docker cli using this repo:
ghcr.io/linuxserver/lychee

## Command used to create docker container (run/create/compose/screenshot)

```
docker run -d \
  --name=lychee \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=America/New_York \
  -e DB_HOST=mariadb \
  -e DB_USERNAME=lychee \
  -e DB_PASSWORD=passwordToDbHere \
  -e DB_DATABASE=lychee \
  -p 8080:80 \
  -v /srv/dev-disk-by-uuid-e790ab10-05b5-4446-be4f-761b1fdd1e7b/appdata/lychee:/config \
  -v /srv/dev-disk-by-uuid-e790ab10-05b5-4446-be4f-761b1fdd1e7b/media/photos:/pictures \
  --restart unless-stopped \
  ghcr.io/linuxserver/lychee
```

## Docker logs

[_lychee_logs-2.txt](https://github.com/linuxserver/docker-lychee/files/6173507/_lychee_logs-2.txt)
[_lychee_logs-1.txt](https://github.com/linuxserver/docker-lychee/files/6173500/_lychee_logs-1.txt)

**Comment by Roxedus** [comment]
From your log:
```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@


Your DockerHost is most likely running an outdated version of libseccomp


To fix this, please visit https://docs.linuxserver.io/faq#libseccomp


Some apps might not behave correctly without this


@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
```

**Comment by kevinlowen1** [comment]
After fixing that issue the problem appears to persist.  Here is the new log the only difference seems to be that section of log you linked is no longer present.

[_lychee_logs.txt](https://github.com/linuxserver/docker-lychee/files/6173663/_lychee_logs.txt)

**Comment by Roxedus** [comment]
It cant connect to the database. `mariadb` wont resolve with the default bridge.

**Comment by kevinlowen1** [comment]
@Roxedus  Can you link to a page that has similar steps to resolve this? I am afraid i do not understand what can be done to remedy this.

I assume what you mean is that the lychee container cannot find the mariadb container with the default bridge networking option.  
Do you think the solution would be to change the settings in the host or the lychee container?

**Comment by Roxedus** [comment]
change `mariadb` to the ip of the server in the `DB_HOST` variable

**Comment by kevinlowen1** [comment]
@Roxedus Actually I just left the container for ~20minutes and it seems that it is working now....I didn't change anything but i will try your suggestion if/when i run into further issues.  I'm going to do some testing for a bit and close the ticket

**Comment by kevinlowen1** [comment]
It appears there is still an issue somewhere.

- I have deleted all the tables in the mariadb database named `lychee`.

- I removed all the config files from the volume after deleting the container.

- I remade the container with `192.168.2.2` instead of mariadb for the DB_HOST

The log shows that the container is able to connect to the db and i do see tables getting created in the db, but it appears there is still some issue somewhere.  If i let it run for long enough i can reach the lychee website at port 8080, but it says the `database version is behind` and asks for the admin username and password.  I just created the docker container for the db yesterday though so i don't think it is behind in reality....

See the below logs for more details on the issue:
[_lychee_logs-6.txt](https://github.com/linuxserver/docker-lychee/files/6173842/_lychee_logs-6.txt)

This is the screen i am presented with after waiting for lychee to start.  I tried putting in the db admin username/password but that did not work.  It just took me to another screen with a 500 error.

![Screen Shot 2021-03-19 at 4 32 03 PM](https://user-images.githubusercontent.com/78703790/111839177-c3885900-88d0-11eb-96bc-82724b4b2410.png)

**Comment by Roxedus** [comment]
post some full logs please

**Comment by kevinlowen1** [comment]
I restarted the container and reset everything after my last post.
This is the log of the startup after that point for the lychee container.

[_lychee_logs.txt](https://github.com/linuxserver/docker-lychee/files/6174441/_lychee_logs.txt)

Once it got to this point I am presented with the screen from the screenshot above.  
The logs for the raspberry pi host is below, I think the only relevant parts will be today's logs.

[syslog.txt](https://github.com/linuxserver/docker-lychee/files/6174459/syslog.txt)

Finally the logs for the mariadb container are below.

[_lychee_db_logs.txt](https://github.com/linuxserver/docker-lychee/files/6174478/_lychee_db_logs.txt)

If there's any other logs you would want to see, let me know, i am glad you are being so helpful!

**Comment by Roxedus** [comment]
So I just looked trough this. It looks to me that this is due to the outdated mariadb version in our image (upstream doesnt publish newer). I see you are on arm64, so you can solve this my using a 64bit OS, and the alpine tag on mariadb(you cannot run this on a 32bit os due to a upstream bug, tracked here linuxserver/docker-mariadb#76)

**Comment by kevinlowen1** [comment]
Ok, I downloaded a 64bit version of the OS and am going to try reinstalling with the suggested mariadb tag.  Will update this ticket when I know if that solved the issue

**Comment by kevinlowen1** [comment]
Im still running into an issue but now it seems to be around mariadb not running as expected before i even get to the lychee install.
I tried with postgres instead and that gets the lychee installation a bit further but i still cannot actually get it running.

I am going to close this issue for now until i can retest with a fully fresh external drive for the containers and a fresh install on the raspberry pi.  Will reference this ticket once i can do that.
