### ISSUE TITLE
Lychee 4.5.3 is out - with many bugfixes

### ISSUE THREAD

**Issue by adrfantini** [linuxserver/docker-lychee#56]
See https://github.com/LycheeOrg/Lychee/releases

It would be nice to see this docker rebuilt with the new Lychee version.

**Comment by aptalca** [comment]
Unfortunately the builds are broken at the moment and the maintainer is busy with real life but it's on the to-do list: https://ci.linuxserver.io/blue/organizations/jenkins/Docker-Pipeline-Builders%2Fdocker-lychee/activity?branch=master

**Comment by mariushosting** [comment]
Any update on this? @aptalca https://github.com/LycheeOrg/Lychee/releases/tag/v4.6.5

**Comment by aptalca** [comment]
https://github.com/linuxserver/docker-lychee/pull/51

**Comment by anthonyrussano** [comment]
@aptalca does that mean the upgrade is available... was that PR approved?

I saw a comment that said we could run

lspipepr/lychee:v4.6.1-pkg-61a4e78d-pr-51

**Comment by anthonyrussano** [comment]
oh wait, I think i see... it's a work in progress. this is very exciting.. glad I checked the issues section

**Comment by anthonyrussano** [comment]
I can test it out... looks like it works so far

**Comment by nemchik** [comment]
Closing. 4.7.0 is released in our `latest` image.
