### ISSUE TITLE
Fresh install on unRAID never connects to database

### ISSUE THREAD

**Issue by technofreak74** [linuxserver/docker-lychee#59]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

1. Install lychee 'app' from the community applications store.
2. Fill out the required template with db credentials etc.
3. Start container.
4. Access web UI

## Current Behavior
Container starts but connections to the web UI are refused indefinitely.
Viewing the log shows it spinning on "Waiting for database connection..."

## Steps to Reproduce
1. Remove any existing lychee appdata folder. (it doesn't hang if the config already exists).
2. Install lychee 'app'
3. Start container.
4. Try to connect to webUI (refused).
5. Check log.

## Environment
**OS:** unRAID 6.11.1
**CPU architecture:** x86_64
**How docker service was installed:**
NAS OS provided.

## Command used to create docker container (run/create/compose/screenshot)
![image](https://user-images.githubusercontent.com/9699636/197352007-e51c30dc-c9b8-4f16-8da0-0c0ca0a1ccf1.png)

## Docker logs
```
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    99
User gid:    100
-------------------------------------

cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/20-config
cont-init: info: /etc/cont-init.d/20-config exited 0
cont-init: info: running /etc/cont-init.d/30-keygen
generating self-signed keys in /config/keys, you can replace these with your own keys if required
Generating a RSA private key
...........................................................................................................................+++++
..+++++
writing new private key to '/config/keys/cert.key'
-----
cont-init: info: /etc/cont-init.d/30-keygen exited 0
cont-init: info: running /etc/cont-init.d/40-config
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
```

**Comment by j0nnymoe** [comment]
`mariadb` won't resolve a containers IP address on the normal bridge network.

**Comment by robclarkoi** [comment]
Sorry, I removed the real address and put it back to the default because I didn't want to confuse things (I thought that was supposed to work and my setup was broken). With the proper address and manually adding a variable DB_PORT set to 3306 it works.

**Comment by technofreak74** [comment]
Sorry, I removed the real address and put it back to the default because I didn't want to confuse things (I thought that was supposed to work and my setup was broken). With the proper address and manually adding a variable DB_PORT set to 3306 it works.

**Comment by technofreak74** [comment]
To be clear. Until the linked PR (or similar) is merged, ALL new installs on unraid will fail (this was not caused by any misconfiguration of my system). The workaround is to manually add a DB_PORT variable to the config (which if you are using the standard port is very counter-intuitive). This is going to be the end of the line for a lot of potential new users, it nearly was for me.
