### ISSUE TITLE
[BUG] BREAKING CHANGE Version 5.0.0: npm steps are required if building from git clone.

### ISSUE THREAD

**Issue by ildyria** [linuxserver/docker-lychee#74]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi, :smile: 

I'm one of the main dev of Lychee.
This is a heads-up on a **breaking change**. :see_no_evil: 

Migration to Version 5 requires two additional steps to generate the front-end:
`npm install`
`npm run build` 

Otherwise you will be presented with this beautiful exception:
```
HttpException
Vite manifest not found, please execute `npm run dev`
```

Note that `npm run dev` is if you want to do development, the files are only temporary.

### Expected Behavior

We added the following steps in our [(LycheeOrg) Dockerfile](https://github.com/LycheeOrg/Lychee-Docker/blob/master/Dockerfile):
```dockerfile
# Multi-stage build: Build static assets
# This allows us to not include Node within the final container
FROM node:20 as node_modules_go_brrr

RUN mkdir /app

RUN mkdir -p  /app
WORKDIR /app
COPY --from=base /var/www/html/Lychee /app

RUN \
    npm ci --no-audit && \
    npm run build

# From our base container created above, we
# create our final image, adding in static
# assets that we generated above
FROM base

# Packages like Laravel Nova may have added assets to the public directory
# or maybe some custom assets were added manually! Either way, we merge
# in the assets we generated above rather than overwrite them
COPY --from=node_modules_go_brrr --chown=www-data:www-data /app/public /var/www/html/Lychee/public-npm
RUN rsync -ar /var/www/html/Lychee/public-npm/ /var/www/html/Lychee/public/ \
    && rm -rf /var/www/html/Lychee/public-npm \
    && chown -R www-data:www-data /var/www/html/Lychee/public
```

Note that this fix does not work with armv6. :(

### Steps To Reproduce

1. Run the docker image normally (with version 5.0.0),
2. try to access Lychee,
3. get the error 500.

### Environment

```markdown
- OS: Any
- How docker service was installed: Does not matter.
```

### CPU architecture

x86-64

### Docker creation

```bash
Does not matter.
```

### Container logs

```bash
Does not matter.
```

**Comment by blaine07** [comment]
On Unraid here - is there a way to run these same "fix" steps on Unraid? Am I able to just roll back versions? What with Unraid is suggested to be done to fix issue?

**Comment by nemchik** [comment]
Should be resolved in https://github.com/linuxserver/docker-lychee/pull/76
I opted to remove the `node_modules` after build runs, but if they need to be keps I will need to apply a few changes to the PR.

Test image is available:
`lspipepr/lychee:v5.0.0-pkg-960de4ce-dev-71c8b6ce0d7a827767352ae10a9af66772066aca-pr-76`

**Comment by ildyria** [comment]
It seems that v5 was not as stable as I hopped: :sob: 
https://github.com/LycheeOrg/Lychee/issues

If you get complaints, you can tell your users the following:
> As a temporary solution, you can disable the Livewire front-end by adding to your .env :
> 
> ```
> LIVEWIRE_ENABLED=false
> ```
